In [1]:
import numpy as np

# Creating a 2D NumPy array
a = np.array([[12, 4, 5], [23, 45, 66], [45, 34, 23]])

# Printing array
print("Printing Array\n")
print(a, "\n")

# Printing NumPy array attributes
print("Printing NumPy array Attributes")
print("1. Array Shape is:", a.shape)
print("2. Array dimensions are", a.ndim)
print("3. Datatype of array is", a.dtype)
print("4. Length of each element of array in bytes is", a.itemsize)
print("5. Number of elements in array are", a.size)

# Seed with a set value to ensure the same random arrays are generated every time
np.random.seed(0)

# Generating random arrays
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

# Printing random arrays
print("\nOne-dimensional array\n", x1)
print("Two-dimensional array\n", x2)
print("Three-dimensional array\n", x3)

Printing Array

[[12  4  5]
 [23 45 66]
 [45 34 23]] 

Printing NumPy array Attributes
1. Array Shape is: (3, 3)
2. Array dimensions are 2
3. Datatype of array is int32
4. Length of each element of array in bytes is 4
5. Number of elements in array are 9

One-dimensional array
 [5 0 3 3 7 9]
Two-dimensional array
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
Three-dimensional array
 [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
